### PR TITLE
Removes react spring from leva

### LINKED ISSUE #44: Remove react-spring from Joystick & folders

### PR DESCRIPTION
**Pull request by dbismut**
Closes #44

### CODE REVIEW

**Comment by marcofugaro** [comment]
Is this a buggerino?

https://user-images.githubusercontent.com/7217420/106356368-670cb280-62ff-11eb-8a34-daf61df3f0d5.mov

**Comment by gsimone** [comment]
Same buggerino when rapidly clicking to toggle

**Comment by dbismut** [comment]
Dammit. I'll check @marcofugaro 

The bug when clicking rapidly on it I did get it but it's really stressing the component.

The problem that I faced was when you set the animation to 0 you need to set the height manually and then set it to 0 to trigger the transition. That's we're I used a `setTimeout` with a `50ms` delay as I need to make sure the browser had the time to invalidate its layout. 

Maybe I'm song something wrong here.

**Comment by marcofugaro** [comment]
@dbismut to force reflow of the DOM, try calling `window.getComputedStyle(el)` instead of the setTimeout

**Comment by dbismut** [comment]
That wasn't it actually, it was a bug with `onTransitionEnd` which is not a very predictable api actually so maybe we would be better off just calling a `setTimeout` of the duration of the css transition. But it works now hopefully.

> `window.getComputedStyle(el)` instead of the setTimeout

Just tried but it doesn't help, the transition doesn't trigger and the animation jumps.

**Review by marcofugaro — APPROVED** [review]
Looks perfect! 🎉

**Pull request merged**
